In [2]:
import numpy as np
import time
import sys

In [3]:
l1 = range(0,10000000)
l2 = range(0,10000000)
l3 = []

a1 = np.arange(1,10000000)
a2 = np.arange(1,10000000)

start = time.time()
for i in l1:
    l3.append(l1[i]+l2[i])
print((time.time()-start)*1000)

start = time.time()
a3 = a1+a2
print((time.time()-start)*1000)

8593.91736984253
31.992673873901367


In [4]:
n = np.arange(12).reshape(-1,3,2)

In [5]:
print(n.ndim)

3


In [6]:
print(n.itemsize)

4


In [7]:
print(n.dtype)

int32


In [8]:
print(n.size)

12


In [9]:
print(n.shape)

(2, 3, 2)


In [10]:
n1 = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])

In [11]:
print(n1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# 5 & 8
print(n1[1:3,1:2])

[[5]
 [8]]


In [13]:
# 4 & 7
print(n1[1:3,0:1])

[[4]
 [7]]


In [14]:
# 1 2 3
print(n1[1:4,0:6])

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
print(n1) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,1+2j]])

# IF we do have a numpy array with integer values and we have put any value other then integer
# the whole array values will get converted to that type
# 1. while put the all interger values
# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])

# 2. while put one value as character
# array([['1', '2', '3'],
#        ['4', '5', '6'],
#        ['7', '8', 'a']], dtype='<U11')

# 3. While put the one value as complex number
# array([[1.+0.j, 2.+0.j, 3.+0.j],
#        [4.+0.j, 5.+0.j, 6.+0.j],
#        [7.+0.j, 8.+0.j, 1.+2.j]])



In [17]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[11,22,33]])

print("print(a.shape)=",a.shape)
print("print(a.dtype)=",a.dtype)
print("print(a.itemsize)=",a.itemsize)
print("print(a.ndim)=",a.ndim)
print("print(a)=\n",a)
print("print(a.max())=",a.max())
print("print(a.min())=",a.min())
print("print(a.mean())=",a.mean())
print("a.reshape(6,2)=\n",a.reshape(6,2))
print("print(a.transpose())=\n",a.transpose())
print("print(a.__len__())=",a.__len__())
print("print(a.fill(1))=",a.fill(1))
print("print(a)=\n",a)


print(a.shape)= (4, 3)
print(a.dtype)= int32
print(a.itemsize)= 4
print(a.ndim)= 2
print(a)=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]]
print(a.max())= 33
print(a.min())= 1
print(a.mean())= 9.25
a.reshape(6,2)=
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 11]
 [22 33]]
print(a.transpose())=
 [[ 1  4  7 11]
 [ 2  5  8 22]
 [ 3  6  9 33]]
print(a.__len__())= 4
print(a.fill(1))= None
print(a)=
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
import numpy as np
array_a = np.random.randint(1,50,70).reshape(7,10)
print(array_a)
'''[[15  7 23 23  9]
    [28 42  7 27 42]
    [25 21  9 18 49]
    [48 32 40 27 11]
    [33  2 37 40 19]
    [28 11 34 29 31]]'''


# Slicing
#  9 18 49
# 40 27 11
print (array_a[2:4,2:]) 

# 42 7
# 21 9
# 32 40

print(array_a[1:4,1:3])

# 15 

print(array_a[0,0])

# 9

print(array_a[0,-1])

# 31 
print(array_a[-1,-1])
 

#[[40 37 47 12 22 32  7 28 39 16]
# [47 13  3  1 34 33 26  2 42 37]
# [47 31 10 49 38 14 49 34 24 14]
# [44 18 13 12 41 26 22  9 20 35]
# [13  2 23 37  9 25 12 49  3 13]
# [13  4 31 41  2 42 21 36 15 37]
# [ 5 25 34 22 24 11 40  6 47 49]]

# 31 10 49 38 14 49 34
# 18 13 12 41 26 22  9
#  2 23 37  9 25 12 49
 
print(array_a[2:5,1:8])
 
# 35
# 13
# 37

print(array_a[3:6,9:])



[[45  2 27 23  3 21 23 46  1 21]
 [34 49 18 22  6  1 35 13 19 25]
 [20 31 30 46 35 16 28 37 17  4]
 [33 36 17 48 40 44 41 26 22 48]
 [ 8  2 42  1  9 28 17 47 21 49]
 [ 8 12 44  8 32 44 43 46 26 35]
 [ 2 14  5 30 35 13 26 35 46  9]]
[[30 46 35 16 28 37 17  4]
 [17 48 40 44 41 26 22 48]]
[[49 18]
 [31 30]
 [36 17]]
45
21
9
[[31 30 46 35 16 28 37]
 [36 17 48 40 44 41 26]
 [ 2 42  1  9 28 17 47]]
[[48]
 [49]
 [35]]


In [19]:
import numpy as np 
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [20]:
np.__version__

'1.18.1'

In [21]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/hp/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users

In [22]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(a.__sizeof__())

arr1.size * arr1.itemsize

160


20

In [23]:

import numpy as np

a = np.random.randint(1,2,400).reshape(20,20)

for i in range(10):
     if(i%2==1):
          a[i:-i,i:-i] = 0
     else:
          a[i:-i,i:-i] = 1
print(a)



[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
