# Numpy Practice

In [1]:
# To import the numpy module 
import numpy as np 

In [2]:
# Creation of teh list
list1 = [1,2,3,4]

In [3]:
# creating the numpy Array using the list object
npa1 = np.array(list1)

In [4]:
# printing the array
print(npa1)
npa1

In [5]:
# Changing dtype we can change the data type of the values according to our data

list1 = [12,34,44,55]
print(type(list1))
arr1 = np.array(list1,dtype="int8")
print(arr1.dtype)
arr1 = np.array(list1,dtype="int16")
print(arr1.dtype)
arr1 = np.array(list1,dtype="int32")
print(arr1.dtype)
arr1 = np.array(list1,dtype="int64")
print(arr1.dtype)
arr1 = np.array(list1,dtype="float32")
print(arr1.dtype)

<class 'list'>
int8
int16
int32
int64
float32


In [6]:
# Creation of the numpy array using the tuple

tup1 = (1,2,3,4,5,6)
print(tup1)
arr1 = np.array(tup1)
print(arr1)
arr1

(1, 2, 3, 4, 5, 6)
[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [7]:
# Getting the Shape of the array

print(arr1.shape)

(6,)


In [8]:
# Two Dimensional Array using the Python Structure

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr1.shape

(3, 3)

In [10]:
arr1.size

9

In [11]:
# Creation of teh zero array

zero_array = np.zeros((3,5))
zero_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
zero_array.shape

(3, 5)

In [13]:
zero_array.size

15

In [14]:
# creation of the array using 'arange()'
# below code will create the array from 0-14
arr1 = np.arange(15)
print(arr1)
# below code will create the array from 1-14
arr2 = np.arange(1,15)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
# linspace()

# Below will create the 10 equi-distance numbers between 1 and 5
arr1 = np.linspace(1,5,10)
print("10 equi-distance numbers between 1 and 5:\n", arr1)

# Below will create the 10 equi-distance numbers between 1 and 5
# using the "round()" we can truncate the decimal places 
arr1 = np.round(np.linspace(1,5,10),2)
print("\n\n10 equi-distance numbers between 1 and 5(With round() to truncate the decimals):\n", arr1)

# Below will create the 4 equi-distance numbers between 1 and 4
arr2 = np.round(np.linspace(1,4,4),2)
print("\n\n4 equi-distance numbers between 1 and 4:\n",arr2)

# Below will create the 20 equi-distance numbers between 1 and 10
arr3 = np.round(np.linspace(1,10,20),2)
print("\n\n20 equi-distance numbers between 1 and 10\n",arr3)



10 equi-distance numbers between 1 and 5:
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


10 equi-distance numbers between 1 and 5(With round() to truncate the decimals):
 [1.   1.44 1.89 2.33 2.78 3.22 3.67 4.11 4.56 5.  ]


4 equi-distance numbers between 1 and 4:
 [1. 2. 3. 4.]


20 equi-distance numbers between 1 and 10
 [ 1.    1.47  1.95  2.42  2.89  3.37  3.84  4.32  4.79  5.26  5.74  6.21
  6.68  7.16  7.63  8.11  8.58  9.05  9.53 10.  ]


In [16]:
# We can create the empty array using the "Empty Function which will 
# craete the array of the metioned size and shape with random values"
emp = np.empty((10,5))
print(emp)

[[            nan 3.44886448e-307 4.28848981e-321 4.94065646e-324
  4.44659081e-321]
 [4.22793571e-307 2.41104035e-321 1.05700260e-307 2.76676762e-321
  2.13620807e-306]
 [4.46635344e-321 4.00536721e-307 4.15015143e-321 6.23040373e-307
  4.03157567e-321]
 [6.23059725e-307 5.35567160e-321 1.00132653e-307 5.49400998e-321
  1.69121095e-306]
 [5.53353523e-321 2.22526738e-307 5.39519685e-321 2.55896905e-307
  5.84973725e-321]
 [3.00401098e-307 1.33508574e-306 3.44898501e-307 2.33645657e-307
  2.44769838e-307]
 [4.45040576e-307 2.78147134e-307 6.89801416e-307 1.33508574e-306
  3.44898501e-307]
 [2.33645657e-307 2.44769838e-307 4.45040576e-307 2.78147134e-307
  6.89801416e-307]
 [4.00536043e-307 1.33508574e-306 3.44898671e-307 4.00536382e-307
  1.61323712e-307]
 [2.67008863e-307 3.56035245e-307 1.61323966e-307 9.34609111e-307
  1.06809792e-306]]


In [17]:
# we can create the array of the same structure using the empty_like()
# below will create the empty array with the structure same as zero_array
emp_1 = np.empty_like(zero_array)
print(emp_1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# We can create the identical matrix array using identity()
a = np.identity(5)
print(a)
print("Size :",a.size)
print("shape:",a.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Size : 25
shape: (5, 5)


In [19]:
# creation of the multi dimensional array using reshape()
# below will create the one dimetional array with 100 numbers
tdim = np.arange(0,80)
print(tdim,"\n\n")

# below will create the 2 dimetional array with 100 numbers in 10x10 format
tdim = np.arange(0,80).reshape(8,10)
print(tdim,"\n\n")

# below will create the 2 dimetional array 
# with 100 numbers when only column parameter is known (20)
tdim1= np.arange(0,80).reshape(-1,20)
print(tdim1,"\n\n")

# below will create the 2 dimetional array 
# with 100 numbers when only column parameter is known (5)
tdim2= np.arange(0,80).reshape(-1,5)
print(tdim2,"\n\n")



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79] 


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]] 


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]] 


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 6

In [20]:
# using teh ravel() we can change the 
# multi dimensional array into one dimensional array

tdim2 = np.arange(0,80).reshape(-1,5)
print("Shape:",tdim2.shape,"\n",tdim2,"\n\n")
odim1 = tdim.ravel()
print("Shape:",odim1.shape,"\n",odim1,"\n\n")

Shape: (16, 5) 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]] 


Shape: (80,) 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79] 




In [21]:
# creating the 2 dimensional array with 3 rows and 3 columns
a1 = np.arange(1,10).reshape(3,3)
a1

# Sum of all the elements 
print("Full Matrix Sum:\t",a1.sum())

# Column Sum
print("Columns Sum:\t\t",a1.sum(axis=0))

# row Sum
print("Row Sum:\t\t",a1.sum(axis=1))

Full Matrix Sum:	 45
Columns Sum:		 [12 15 18]
Row Sum:		 [ 6 15 24]


In [22]:
# Transposing the matrix using transpose() or T

print(" Original:\n",a1,"\n\n","Transposed:\n",a1.transpose())
print("\n\n Original:\n",a1,"\n\n","Transposed:\n",a1.T)

 Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 Transposed:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


 Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 Transposed:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
a1.flat

In [24]:
# using flat we can iterate through the array elements 
for i in a1.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [26]:
# We can get the informtion about how many bytes our array is consuming
a1.nbytes

36

# IMPORTANT : there are attribute and functions 
# array.abc : Calling attribute
# array.abd() : Calling function

In [34]:
# Argmax() : Provides the position of the max element in array
a = np.array([1,2,32,3,4,13]) # max is 32 and index is at 2 
print(a.argmax())

a = np.array([1,2,32,322,433,13]) # max is 433 and index at 4
print(a.argmax())


2
4


In [36]:
# Argmin() : Provides the index position of the min element in array
a = np.array([13,12,32,3,4,13]) # min is 3 and index is at 3 
print(a.argmin())

a = np.array([331,222,3233,32222,433,131]) # mix is 131 and index at 5
print(a.argmin())


3
5


In [39]:
# argsort() : Gives the array with the positional index in the sorted array
a = np.array([331,222,3233,32222,433,131])
a.argsort()
# array([5,   1,   0,   4,   2,   3]
#       131   222  331  433  3233 32222

array([5, 1, 0, 4, 2, 3], dtype=int64)

In [40]:
a

array([  331,   222,  3233, 32222,   433,   131])

In [41]:
a.data

In [42]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [46]:
a.size * a.itemsize

24

In [78]:
# Numpy array does take very less space. TO proof let us see

# importing the sys module
import sys

# creating a Python List
py_a=[1,2,3,4,5]
print(sys.getsizeof(py_a))

# getting the size of the List
size_py_a = len(py_a)*sys.getsizeof(py_a)
print("Memory Space taken by the List:\t\t",size_py_a)

# Creating the array using Pythn list
np_a = np.array(py_a)

# Calculating the size of the array
size_np_a = np_a.size*len(np_a)
print("Memory Space taken by the Numpy Array:\t",size_np_a)

104
Memory Space taken by the List:		 520
Memory Space taken by the Numpy Array:	 25
